"""add price_at_purchase to OrderItem

Revision ID: 18c4af47d098
Revises: dd7fada0280e
Create Date: 2025-09-30 17:41:51.222922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18c4af47d098'
down_revision: Union[str, Sequence[str], None] = 'dd7fada0280e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('price_at_purchase', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'price_at_purchase')
    # ### end Alembic commands ###
