"""add driver info to order model

Revision ID: 4e68460c5348
Revises: e236d41980f5
Create Date: 2025-10-02 01:32:56.160496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e68460c5348'
down_revision: Union[str, Sequence[str], None] = 'e236d41980f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('driver_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'users', ['driver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'driver_id')
    # ### end Alembic commands ###
