"""add_store_locations

Revision ID: 6a482f90e49e
Revises: 53c7cf35be4c
Create Date: 2026-01-24 20:24:58.542689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a482f90e49e'
down_revision: Union[str, Sequence[str], None] = '53c7cf35be4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('stores', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('stores', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'is_active')
    op.drop_column('stores', 'longitude')
    op.drop_column('stores', 'latitude')
    # ### end Alembic commands ###
