"""add_banner_url_to_store

Revision ID: 797246f719ab
Revises: a36b43accd2b
Create Date: 2026-01-29 16:39:51.944627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '797246f719ab'
down_revision: Union[str, Sequence[str], None] = 'a36b43accd2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('banner_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'banner_url')
    # ### end Alembic commands ###
