"""add_group_id_to_order

Revision ID: 7d18d8967445
Revises: 797246f719ab
Create Date: 2026-01-30 13:11:44.477046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d18d8967445'
down_revision: Union[str, Sequence[str], None] = '797246f719ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('group_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_orders_group_id'), 'orders', ['group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_group_id'), table_name='orders')
    op.drop_column('orders', 'group_id')
    # ### end Alembic commands ###
