"""minor_polishing

Revision ID: 958616b03769
Revises: b0190a94fe97
Create Date: 2026-01-28 21:21:55.856447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '958616b03769'
down_revision: Union[str, Sequence[str], None] = 'b0190a94fe97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('category', sa.String(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('products', 'category')
    op.drop_column('addresses', 'created_at')
    # ### end Alembic commands ###
