"""add_image_url_to_store_and_product

Revision ID: a36b43accd2b
Revises: 958616b03769
Create Date: 2026-01-29 12:06:07.557039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a36b43accd2b'
down_revision: Union[str, Sequence[str], None] = '958616b03769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('stores', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'image_url')
    op.drop_column('products', 'image_url')
    # ### end Alembic commands ###
