"""add owner_id to stores table

Revision ID: c848ffc1872e
Revises: 0b0398adb849
Create Date: 2025-10-02 01:50:31.284218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c848ffc1872e'
down_revision: Union[str, Sequence[str], None] = '0b0398adb849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stores', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.drop_column('stores', 'owner_id')
    # ### end Alembic commands ###
