"""add cascade delete and eager loading for Order,and unique constraint on order_id + product_id

Revision ID: dd7fada0280e
Revises: 6d1723491ba5
Create Date: 2025-09-30 17:35:27.576637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd7fada0280e'
down_revision: Union[str, Sequence[str], None] = '6d1723491ba5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_order_product', 'order_items', ['order_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_order_product', 'order_items', type_='unique')
    # ### end Alembic commands ###
