"""add owner to store model

Revision ID: 0b0398adb849
Revises: 4e68460c5348
Create Date: 2025-10-02 01:41:01.433314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b0398adb849'
down_revision: Union[str, Sequence[str], None] = '4e68460c5348'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'store_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('stores', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'description')
    op.alter_column('products', 'store_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
